# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e1ad13f3fdc850a3fc31e4cfff0cffaedacee69b8aa03fbe6ca7495d5a95fafc91bd51a4b7ea9343878762416d1886b064f342be6d32bc135c52fea8c5a0361

test:
  secret_key_base: 7408bca71c30281c983a37c4380882b524b2333840947297999523b4ce56ff5b9faf78f975aab53e8574c36c53514b72ec4d2b85968af8a1297025e9c67a4170

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
